import type { Metadata } from 'next'
import './globals.css'
import { Providers } from '../providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex font-mono min-h-screen flex-col items-center justify-center p-4">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  )
}
